import Head from 'next/head'
import { Container, Row, Col, ListGroup } from 'react-bootstrap'
import NavbarComponent from '../../components/navbar'
import Footer from '../../components/footer'
import { FadeUpRef } from '../../components/scroll-fade-ref'

export default () => {
  return (
    <>
      <Head>
        <title>Tetris - OJII3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />

      <main>
        <Container fluid className='fade-up'>
          <Row className='p-5'>
            <h1 className='text-center'>
              Tetris-ish Browser Game
            </h1>
          </Row>
          <Row>
            <h2 className='text-center'>with Pure JavaScript</h2>
          </Row>

          <Row className='p-5'>
            <Col className='text-center'>
              <p>
                See code in{' '}
                <a href='https://github.com/ojii3/ojii3.github.io'>GitHub</a>
              </p>
            </Col>
          </Row>

          <Row className='justify-content-md-center p-5' ref={new FadeUpRef().ref}>
            <Col sm={3}>
              <h2 className='text-center'>Feature</h2>
              <ListGroup variant='flush'>
                <ListGroup.Item><li>Without any game engine</li></ListGroup.Item>
              </ListGroup>
            </Col>
          </Row>
          <Row className='justify-content-md-center p-5' ref={new FadeUpRef().ref}>
            <Col sm={3}>
              <h2 className='text-center'>What I used</h2>
              <ListGroup variant='flush'>
                <ListGroup.Item><li>Google Apps Script</li></ListGroup.Item>
                <ListGroup.Item><li>canvas API (HTML5)</li></ListGroup.Item>
              </ListGroup>
            </Col>
          </Row>

        </Container>
      </main>

      <Footer />
    </>
  )
}